(() => {
  'use strict';

  // MineTools content script. Generated by scripts/build.mjs.
  // Chrome ISOLATED world; no page-script bridge or remote code.
  if (!document.body) return { ok: false };
  const KEY = '__mineToolsPanel';
  const PANEL_ID = 'minetools-panel';
  window[KEY]?.destroy?.();
  document.getElementById(PANEL_ID)?.remove();
  const METRIC = '.aitdk-site-metrics-container';
  const EXCLUDED = `${METRIC}, #${PANEL_ID}, .mslg, [data-sitelink], #tads, #bottomads, [data-text-ad], .related-question-pair`;
  const COLUMNS = ['#', 'site', 'page url', 'page title', 'page desc', 'domain created', 'monthly visits', 'avg. visit duration'];
  const clean = value => String(value ?? '').replace(/\s+/g, ' ').trim();
  const text = node => clean(node?.innerText ?? node?.textContent);
  const visible = node => !!node?.getClientRects().length &&
    getComputedStyle(node).visibility !== 'hidden' && !node.closest('[hidden], [aria-hidden="true"]');
  const hostOf = value => {
    try { return new URL(value).hostname.toLowerCase().replace(/^www\./, '').replace(/\.$/, ''); }
    catch { return null; }
  };
  const isGoogle = host => /(^|\.)google\.(?:com|[a-z]{2}|(?:com|co)\.[a-z]{2})$/i.test(host);
  const sameHost = (a, b) => !!a && !!b && a === b;
  const selectText = (root, selectors) => {
    for (const selector of selectors) {
      for (const node of root.querySelectorAll(selector)) {
        if (visible(node) && text(node)) return text(node);
      }
    }
    return null;
  };

  function readLink(anchor) {
    const raw = anchor.getAttribute('href');
    if (!raw || raw.startsWith('#')) return null;
    let url;
    try { url = new URL(raw, location.href); } catch { return null; }
    if (!/^https?:$/.test(url.protocol)) return null;
    const googleRedirect = u => isGoogle(u.hostname) && /^\/(?:url|goto)\/?$/.test(u.pathname);
    // 仅返回真实目标 URL；不能解码的跳转链接绝不进入展示或导出数据。
    for (let i = 0; i < 3 && googleRedirect(url); i++) {
      const target = url.searchParams.get('url') || url.searchParams.get('q');
      if (!/^https?:\/\//i.test(target || '')) break;
      try { url = new URL(target); } catch { break; }
    }
    let unresolved = googleRedirect(url);
    if (unresolved) {
      for (const attribute of ['data-href', 'data-url', 'data-rurl']) {
        const value = anchor.getAttribute(attribute);
        if (!/^https?:\/\//i.test(value || '')) continue;
        try {
          const target = new URL(value);
          if (!isGoogle(target.hostname)) { url = target; unresolved = false; break; }
        } catch { /* 不完整的目标地址跳过。 */ }
      }
    }
    if (isGoogle(url.hostname) && !unresolved && /^\/(?:search|webhp|preferences|setprefs)(?:\/|$)/.test(url.pathname)) return null;
    if (isGoogle(url.hostname) && /^\/(?:imgres|aclk|pagead)(?:\/|$)/.test(url.pathname)) return null;
    return { url: unresolved ? null : url.href, urlKind: unresolved ? 'display-only' : 'destination' };
  }

  const imageHeading = node => /^(?:images?|image results|图片|圖片|图像|圖像)(?:\s*[:：].*)?$/i.test(text(node));
  const isImageLink = anchor => {
    try {
      const url = new URL(anchor.getAttribute('href'), location.href);
      return isGoogle(url.hostname) && (url.pathname === '/imgres' ||
        (url.pathname === '/search' && (url.searchParams.get('udm') === '2' || url.searchParams.get('tbm') === 'isch')));
    } catch { return false; }
  };
  function findImageResults(root) {
    const modules = [];
    const add = node => {
      if (!node || !visible(node) || node.closest(EXCLUDED) || modules.some(other => other.contains(node))) return;
      for (let i = modules.length - 1; i >= 0; i--) if (node.contains(modules[i])) modules.splice(i, 1);
      modules.push(node);
    };
    for (const node of root.querySelectorAll('[data-attrid="images universal"], [data-attrid="images"], [data-attrid="image pack"]')) add(node);
    for (const heading of root.querySelectorAll('h2, h3, [role="heading"]')) {
      if (!imageHeading(heading) || !visible(heading) || heading.closest(EXCLUDED)) continue;
      for (let node = heading.parentElement; node && node !== root; node = node.parentElement) {
        const hasImages = [...node.querySelectorAll('img')].some(img => visible(img) && img.getBoundingClientRect().width >= 48 && img.getBoundingClientRect().height >= 48);
        if (hasImages || [...node.querySelectorAll('a[href]')].some(isImageLink)) { add(node); break; }
        // 不跨入相邻的普通网页结果。
        if ([...node.querySelectorAll('h3')].some(h3 => !imageHeading(h3) && (h3.closest('a[href]') || h3.querySelector('a[href]')))) break;
      }
    }
    // 没有 Images 标题的独立图片结果；不把网页结果旁的缩略图重复计入。
    for (const anchor of root.querySelectorAll('a[href]')) {
      if (!isImageLink(anchor) || !anchor.querySelector('img') || !visible(anchor) || anchor.closest(EXCLUDED)) continue;
      const card = anchor.closest('.MjjYud, .g, [data-hveid]');
      const webHeading = card && [...card.querySelectorAll('h3')].some(h3 => {
        const link = h3.closest('a[href]') || h3.querySelector('a[href]');
        return link && !isImageLink(link) && !imageHeading(h3);
      });
      if (!webHeading) add(anchor);
    }
    return modules.map(marker => ({ marker, type: 'image', site: 'image', title: 'image',
      url: null, urlKind: 'image', displayURL: null, domain: null }));
  }

  const pageAddress = result => result.url || result.displayURL || (result.type === 'image' ? 'image' : null);
  const metricValue = (result, key) => result.type === 'image' ? '--' : result[key];

  function domainAgeTone(value, today = new Date()) {
    const match = clean(value).match(/^(\d{4})-(\d{2})-(\d{2})$/);
    if (!match) return 'tone-black';
    const [, year, month, day] = match.map(Number);
    const created = new Date(year, month - 1, day);
    const current = new Date(today.getFullYear(), today.getMonth(), today.getDate());
    if (created.getFullYear() !== year || created.getMonth() !== month - 1 || created.getDate() !== day || created > current) return 'tone-black';
    // 按本地日历的周年日判断；2 月 29 日在非闰年以 2 月 28 日为周年日。
    const anniversary = years => new Date(year + years, month - 1,
      Math.min(day, new Date(year + years, month, 0).getDate()));
    if (current < anniversary(1)) return 'tone-dark-blue';
    if (current < anniversary(2)) return 'tone-light-blue';
    return 'tone-black';
  }

  function visitsTone(value) {
    const match = clean(value).match(/^((?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d+)?)\s*([KMB])?$/i);
    if (!match) return 'tone-black';
    const visits = Number(match[1].replace(/,/g, '')) * ({ K: 1e3, M: 1e6, B: 1e9 }[match[2]?.toUpperCase()] || 1);
    if (!Number.isFinite(visits)) return 'tone-black';
    if (visits > 100e6) return 'tone-dark-blue';
    // 超过 1M 和超过 10M 按同一浅蓝色规则展示；恰好 100M 仍为浅蓝色。
    return visits > 1e6 ? 'tone-light-blue' : 'tone-black';
  }

  function isInnerPage(result) {
    if (result.type === 'image') return false;
    if (result.url) {
      try { return /[^/]/.test(new URL(result.url).pathname); } catch { return false; }
    }
    // 加密跳转仍仅显示原有 cite 文本；可见路径只用于着色，不拼接目标链接。
    const display = clean(result.displayURL).replace(/^https?:\/\//i, '');
    const suffix = display.replace(/^[^\s/›>? #]+/, '').split(/[?#]/)[0];
    return /^[\s/›>]+\S/.test(suffix) && /[^\s/›>]/.test(suffix);
  }

  function readMetric(node) {
    const links = [...node.querySelectorAll('a[href]')];
    let domain = null;
    for (const a of links) {
      try {
        const u = new URL(a.getAttribute('href'), location.href);
        if (!/(^|\.)aitdk\.com$/i.test(u.hostname)) continue;
        const match = u.pathname.match(/^\/(?:traffic|whois)\/([^/]+)/i);
        if (match) domain = hostOf('https://' + decodeURIComponent(match[1]));
        if (domain) break;
      } catch { /* 不可解析的指标链接跳过。 */ }
    }
    const labels = {
      domainCreated: /Domain\s*Created\s*[:：]\s*/i,
      monthlyVisits: /Monthly\s*Visits\s*[:：]\s*/i,
      avgVisitDuration: /Avg\.?\s*Visit\s*Duration\s*[:：]\s*/i
    };
    const data = { domain, domainCreated: null, monthlyVisits: null, avgVisitDuration: null };
    for (const [key, label] of Object.entries(labels)) {
      const item = links.find(a => label.test(text(a)));
      const source = text(item || node);
      const match = label.exec(source);
      if (!match) continue;
      const value = source.slice(match.index + match[0].length)
        .split(/(?:Domain\s*Created|Monthly\s*Visits|Avg\.?\s*Visit\s*Duration)\s*[:：]/i)[0].trim();
      data[key] = /^(?:|[-—–]|N\/?A|null|undefined|loading(?:\.{3}|…)?|加载中(?:\.{3}|…)?)$/i.test(value) ? null : value;
    }
    return { node, data };
  }

  function readLocation() {
    const footer = document.querySelector('#footcnt, #fbar, footer, [role="contentinfo"]');
    if (!footer) return { location: null, locationSource: null, locationText: null };
    const address = selectText(footer, ['#uule', '.AhYzQb', '.KS5Qr', '[data-location]', '.unknown_loc + span', '.known_loc + span']);
    const source = selectText(footer, ['.KwU3F']);
    return { location: address, locationSource: source, locationText: text(footer) || null };
  }

  function extract() {
    const pageURL = new URL(location.href);
    const root = document.querySelector('#rso') || document.querySelector('#search') || document.querySelector('main');
    const candidates = root ? findImageResults(root) : [];
    const imageResults = [...candidates];
    if (root) {
      const seen = new Set();
      for (const h3 of root.querySelectorAll('h3')) {
        if (!visible(h3) || h3.closest(EXCLUDED) || imageResults.some(r => r.marker.contains(h3) || h3.contains(r.marker)) || imageHeading(h3)) continue;
        const a = h3.closest('a[href]') || h3.querySelector('a[href]');
        const link = a && readLink(a);
        if (!link || !text(h3) || seen.has(a)) continue;
        seen.add(a);
        const headingArea = h3.closest('.yuRUbf') || a;
        const displayURL = text(headingArea.querySelector('cite')) || null;
        const displayHost = displayURL?.match(/^(?:https?:\/\/)?([^\s/›>]+)/i)?.[1];
        const domain = link.url ? hostOf(link.url) : hostOf('https://' + (displayHost || ''));
        candidates.push({ marker: h3, a, type: 'web', ...link, title: text(h3), displayURL,
          site: selectText(headingArea, ['.VuuXrf', '.site-name']) || domain, domain });
      }
    }
    candidates.sort((a, b) => a.marker.compareDocumentPosition(b.marker) & Node.DOCUMENT_POSITION_FOLLOWING ? -1 : 1);
    // 每条结果只向上扩展到包含自身标题的区域，不跨过另一条结果。
    for (const result of candidates) {
      let card = result.marker;
      while (card.parentElement && card.parentElement !== root) {
        const parent = card.parentElement;
        if (candidates.some(other => other !== result && parent.contains(other.marker))) break;
        card = parent;
      }
      result.card = card;
      if (result.type === 'web') {
        result.displayURL ||= selectText(card, ['cite']);
        const displayedHost = result.displayURL?.match(/^(?:https?:\/\/)?([^\s/›>]+)/i)?.[1];
        result.domain ||= hostOf('https://' + (displayedHost || ''));
        result.site = selectText(card, ['.VuuXrf', '.site-name']) || result.site || result.domain;
      }
    }
    const strips = [...document.querySelectorAll(METRIC)].filter(visible).map(readMetric);
    const matches = new Map();
    const compatible = (result, strip) => !strip.data.domain || !result.domain ||
      sameHost(result.domain, strip.data.domain) || result.domain.endsWith('.' + strip.data.domain);
    const assign = (result, strip, method) => {
      const existing = matches.get(result);
      const completeness = entry => ['domainCreated', 'monthlyVisits', 'avgVisitDuration'].filter(k => entry.data[k] !== null).length;
      if (!existing || completeness(strip) > completeness(existing)) matches.set(result, { ...strip, method });
    };
    for (const strip of strips) {
      const local = candidates.filter(r => r.card.contains(strip.node));
      if (local.length === 1) {
        if (local[0].type === 'web' && compatible(local[0], strip)) assign(local[0], strip, 'result-container');
        continue; // 容器内域名冲突时不借用别条结果的指标。
      }
      // 支持指标条作为结果卡片的紧邻后置兄弟节点。
      let siblingOwner = null;
      for (let branch = strip.node; branch && branch !== root && root?.contains(branch); branch = branch.parentElement) {
        let prev = branch.previousElementSibling;
        while (prev && (prev.matches('script, style, template') || (!text(prev) && !prev.querySelector('h3') && !candidates.some(r => prev.contains(r.marker))))) prev = prev.previousElementSibling;
        const owners = prev ? candidates.filter(r => prev.contains(r.marker)) : [];
        if (owners.length === 1) { siblingOwner = owners[0]; break; }
        if (owners.length > 1) break;
        if (candidates.some(r => branch.contains(r.marker))) break;
      }
      if (siblingOwner) {
        if (siblingOwner.type === 'web' && compatible(siblingOwner, strip)) assign(siblingOwner, strip, 'following-sibling');
        continue;
      }
      // 全页兜底只允许唯一域名 + 唯一指标条；同域多结果不互相借用。
      const byDomain = candidates.filter(r => r.type === 'web' && sameHost(r.domain, strip.data.domain));
      if (byDomain.length === 1 && strips.filter(s => sameHost(s.data.domain, strip.data.domain)).length === 1 && !matches.has(byDomain[0])) {
        assign(byDomain[0], strip, 'unique-domain');
      }
    }
    const results = candidates.map((r, i) => {
      const metric = matches.get(r);
      const description = r.type === 'image' ? 'image' : selectText(r.card, ['.VwiC3b', '.aCOpRe', '.IsZvec', '.s3v9rd', '.ITZIwc', '[data-sncf="1"]', '[data-sncf="2"]', '.st']);
      return { index: i + 1, type: r.type, site: r.site, title: r.title, url: r.url, urlKind: r.urlKind,
        displayURL: r.displayURL, domain: r.domain, description,
        domainCreated: metric?.data.domainCreated ?? null,
        monthlyVisits: metric?.data.monthlyVisits ?? null,
        avgVisitDuration: metric?.data.avgVisitDuration ?? null,
        metricsDomain: metric?.data.domain ?? null, metricsMatch: metric?.method ?? null };
    });
    return {
      googleDomain: pageURL.hostname,
      keyword: pageURL.searchParams.get('q') ?? document.querySelector('textarea[name="q"], input[name="q"]')?.value ?? null,
      totalSearchResults: selectText(document, ['.aitdk-search-result-count-value']),
      ...readLocation(), collectedAt: new Date().toISOString(),
      resultCount: results.length, metricsContainerCount: strips.length, results
    };
  }

  // 页面文字始终作为文字写入，避免标题/描述中的 HTML 被执行。
  const esc = value => (value == null || value === '' ? '未获取' : String(value))
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/([`*_\[\]])/g, '\\$1')
    .replace(/\r?\n/g, '<br>');
  function toMarkdown(data) {
    const rows = data.results.map(r => `| ${r.index} | ${esc(r.site)} | ${esc(pageAddress(r))} | ${esc(r.title)} | ${esc(r.description)} | ${esc(metricValue(r, 'domainCreated'))} | ${esc(metricValue(r, 'monthlyVisits'))} | ${esc(metricValue(r, 'avgVisitDuration'))} |`);
    return [
      '# Google 搜索结果', '',
      `- Google 域名：${esc(data.googleDomain)}`,
      `- 页面定位地址：${esc(data.location)}`, `- 定位来源：${esc(data.locationSource)}`,
      ...(!data.location && data.locationText ? [`- 页脚原文（定位未识别）：${esc(data.locationText)}`] : []),
      `- 搜索关键词：${esc(data.keyword)}`, `- 总搜索结果条数：${esc(data.totalSearchResults)}`,
      `- 采集时间：${data.collectedAt}`, `- 本页提取条数：${data.resultCount}`, '',
      `| ${COLUMNS.join(' | ')} |`,
      `| ${COLUMNS.map(() => '---').join(' | ')} |`, ...rows, '',
      '注：图片行指标以 -- 占位；未获取表示页面未显示或无法可靠匹配；AITDK 指标为扩展显示值。'
    ].join('\n');
  }

  const host = document.createElement('div');
  host.id = PANEL_ID;
  host.style.cssText = 'all:initial!important;position:fixed!important;z-index:2147483647!important;top:20px!important;right:20px!important;display:block!important;';
  const shadow = host.attachShadow({ mode: 'open' });
  const el = (tag, content, className) => {
    const node = document.createElement(tag);
    if (content != null) node.textContent = content;
    if (className) node.className = className;
    return node;
  };
  const style = el('style', `
    :host{color-scheme:light;font:14px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif;color:#182434}
    *{box-sizing:border-box} [hidden]{display:none!important}
    .panel{width:min(1180px,calc(100vw - 24px));max-height:calc(100vh - 24px);display:flex;flex-direction:column;background:#fff;border:1px solid #cbd5e1;border-radius:10px;box-shadow:0 16px 64px #0f172a30;overflow:hidden;position:relative}
    .header{display:flex;align-items:center;gap:8px;padding:7px 10px;background:#142b42;color:#fff;cursor:move;touch-action:none;user-select:none;flex:none;min-height:42px}
    .title{flex:1;min-width:0;font-size:15px;font-weight:650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.hint{font-size:10px;color:#c0d1e2;font-weight:400;margin-left:10px}
    button{font:inherit;font-size:12px;border:1px solid #cbd5e1;border-radius:5px;padding:4px 8px;background:#fff;color:#182434;cursor:pointer;white-space:nowrap}
    button:hover{background:#edf3f9}button:focus-visible{outline:3px solid #2f82e2;outline-offset:2px}button:disabled{opacity:.6;cursor:wait}
    .header button{background:transparent;color:#fff;border-color:#698096}.header button:hover{background:#29465f}.header .primary{background:#d8f5ec;color:#124e43;border-color:#d8f5ec}.header .primary:hover{background:#bcebdc}
    .body{display:flex;flex-direction:column;min-height:0;overflow:hidden}
    .meta{margin:0;padding:6px 10px;display:grid;gap:3px;background:#f7fafc;font-size:11px;line-height:18px;flex:none}
    .meta-line{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr) minmax(0,1.4fr);gap:16px;min-width:0}.meta-item{display:flex;gap:7px;min-width:0;align-items:baseline}
    dt{color:#62758a;flex:none;white-space:nowrap}dd{margin:0;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#243a50}.stats{font-size:11px;color:#62758a;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-align:right}
    .table-wrap{overflow:auto;min-height:0;flex:1 1 auto;border-top:1px solid #e2e8f0}table{border-collapse:collapse;table-layout:fixed;width:100%;font-size:12px;min-width:980px}
    th{position:sticky;top:0;background:#edf3f7;text-align:left;color:#53657a;font-weight:600;z-index:1;padding:4px 6px;line-height:14px;overflow-wrap:normal}td{padding:3px 6px;vertical-align:top}td,th{border-bottom:1px solid #e2e8f0}tbody tr:nth-child(even){background:#fafcfe}tbody tr:hover{background:#f1f7fb}
    .cell-value{max-height:32px;line-height:16px;overflow:hidden;overflow-wrap:anywhere;overscroll-behavior:contain;scrollbar-width:none;scrollbar-color:#b4c6d5 transparent}.cell-value.is-scrollable{overflow-y:auto}.cell-value.is-scrollable:hover,.cell-value.is-scrollable:focus-within{scrollbar-width:thin}.cell-value::-webkit-scrollbar{width:0;height:0}.cell-value:hover::-webkit-scrollbar,.cell-value:focus-within::-webkit-scrollbar{width:4px}.cell-value::-webkit-scrollbar-button{display:none}.cell-value::-webkit-scrollbar-thumb{background:#b4c6d5;border-radius:4px}.cell-value:focus-visible{outline:2px solid #2f82e2;outline-offset:-2px}a{color:inherit;text-decoration:none}a:hover{text-decoration:underline}
    .tone-black{color:#000}.tone-dark-blue{color:#1e3a8a}.tone-light-blue{color:#367bc3}.page-url{color:#000}.page-url.is-inner-page{color:#1260b5}
    .footer{display:flex;align-items:center;gap:16px;flex:none;padding:4px 10px;border-top:1px solid #e2e8f0;min-height:25px}.footer details{flex:none}summary{cursor:pointer;color:#52657a;font-size:11px;line-height:16px}pre{position:absolute;left:8px;right:8px;bottom:25px;z-index:3;margin:0;font:11px/1.6 ui-monospace,monospace;max-height:min(300px,55vh);overflow:auto;background:#f2f6fa;padding:10px;border:1px solid #cbd5e1;border-radius:7px;box-shadow:0 4px 18px #0f172a25}
    .status{color:#62758a;font-size:10px;line-height:16px;min-width:0;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}.manual{position:absolute;bottom:25px;left:8px;right:8px;z-index:4;background:#fff;padding:10px;border:1px solid #cbd5e1;border-radius:7px;box-shadow:0 4px 18px #0f172a25}.manual textarea{width:100%;height:min(150px,35vh);font:12px/1.5 monospace}.manual p{font-size:12px;margin:0 0 6px}
    @media(max-width:760px){.hint{display:none}.meta-line{gap:8px;grid-template-columns:minmax(0,1fr) minmax(0,1fr) minmax(0,.8fr)}.meta-item{gap:4px}.stats{text-align:left}}
  `);
  const panel = el('section', null, 'panel');
  panel.setAttribute('role', 'region');
  panel.setAttribute('aria-label', 'MineTools 搜索结果采集面板');
  const header = el('div', null, 'header');
  const title = el('div', 'MineTools', 'title');
  title.append(el('span', 'Google 搜索采集 · 拖动此处移动面板', 'hint'));
  const collapse = el('button', '−');
  collapse.setAttribute('aria-label', '收起面板');
  collapse.setAttribute('aria-expanded', 'true');
  const close = el('button', '×');
  close.setAttribute('aria-label', '关闭面板');
  const body = el('div', null, 'body');
  const copy = el('button', '复制 Markdown', 'primary');
  const refresh = el('button', '重新提取');
  header.append(title, copy, refresh, collapse, close);
  const meta = el('dl', null, 'meta');
  const stats = el('div', null, 'stats');
  const tableWrap = el('div', null, 'table-wrap');
  const table = el('table');
  const colgroup = el('colgroup');
  // 描述列吸收剩余宽度，确保最后三列不会按比例拉伸。
  for (const width of ['34px', '10%', '17%', '17%', null, '110px', '110px', '110px']) {
    const col = el('col');
    if (width) col.style.width = width;
    colgroup.append(col);
  }
  const thead = el('thead');
  const tr = el('tr');
  COLUMNS.forEach(s => tr.append(el('th', s)));
  thead.append(tr);
  const tbody = el('tbody');
  table.append(colgroup, thead, tbody);
  tableWrap.append(table);
  const details = el('details');
  const json = el('pre');
  details.append(el('summary', '查看结构化 JSON'), json);
  const manual = el('div', null, 'manual');
  manual.hidden = true;
  manual.append(el('p', '浏览器未允许自动复制。下方内容已选中，可按 Ctrl+C / ⌘C 复制。'));
  const textarea = el('textarea');
  textarea.readOnly = true;
  textarea.setAttribute('aria-label', '手动复制 Markdown');
  manual.append(textarea);
  const status = el('div', '自动更新 · 单元格最多两行，滚动查看全文', 'status');
  status.setAttribute('role', 'status');
  const footer = el('div', null, 'footer');
  footer.append(details, status);
  body.append(meta, tableWrap, footer, manual);
  panel.append(header, body);
  shadow.append(style, panel);
  document.documentElement.append(host);
  let data, signature = '', timer = null, disposed = false;
  const controller = new AbortController();
  const on = (node, event, handler) => node.addEventListener(event, handler, { signal: controller.signal });

  function update(force = false) {
    if (disposed) return;
    const next = extract();
    const nextSignature = JSON.stringify({ ...next, collectedAt: null });
    if (!force && signature === nextSignature) return;
    signature = nextSignature;
    data = next;
    meta.replaceChildren();
    for (const fields of [
      [['Google 域名', data.googleDomain], ['定位地址', data.location], ['定位来源', data.locationSource]],
      [['搜索关键词', data.keyword], ['总搜索结果条数', data.totalSearchResults]]
    ]) {
      const line = el('div', null, 'meta-line');
      for (const [label, value] of fields) {
        const item = el('div', null, 'meta-item');
        const description = el('dd', value || '未获取');
        description.title = value || '未获取';
        item.append(el('dt', label), description);
        line.append(item);
      }
      meta.append(line);
    }
    const matched = data.results.filter(r => r.metricsMatch).length;
    stats.textContent = `本页 ${data.resultCount} 条 · AITDK ${matched} 条 · ${new Date(data.collectedAt).toLocaleTimeString()}`;
    stats.title = `页面共 ${data.metricsContainerCount} 个 AITDK 指标条；${stats.textContent}`;
    meta.lastElementChild.append(stats);
    tbody.replaceChildren();
    const cell = (value, column, tone = '') => {
      const td = el('td');
      const content = el('div', value ?? '未获取', `cell-value ${tone}`.trim());
      content.title = String(value ?? '未获取');
      content.setAttribute('aria-label', `${column} 完整内容`);
      td.append(content);
      return td;
    };
    for (const result of data.results) {
      const row = el('tr');
      row.append(cell(result.index, '#'), cell(result.site, 'site'));
      const address = cell(pageAddress(result), 'page url', `page-url${isInnerPage(result) ? ' is-inner-page' : ''}`);
      if (result.url) {
        const link = el('a', result.url);
        link.href = result.url;
        link.target = '_blank';
        link.rel = 'noopener noreferrer';
        address.firstElementChild.replaceChildren(link);
      }
      row.append(address, cell(result.title, 'page title'), cell(result.description, 'page desc'),
        cell(metricValue(result, 'domainCreated'), 'domain created', domainAgeTone(result.domainCreated)),
        cell(metricValue(result, 'monthlyVisits'), 'monthly visits', visitsTone(result.monthlyVisits)),
        cell(metricValue(result, 'avgVisitDuration'), 'avg. visit duration'));
      tbody.append(row);
    }
    if (!data.results.length) {
      const row = el('tr'), cell = el('td', '未识别到网页搜索结果。请确认处于 Google 网页搜索结果页，并等待页面加载后重新提取。');
      cell.colSpan = COLUMNS.length;
      row.append(cell);
      tbody.append(row);
    }
    json.textContent = JSON.stringify(data, null, 2);
    if (!manual.hidden) textarea.value = toMarkdown(data);
    clampPosition();
    updateCellFocus();
  }

  function updateCellFocus() {
    for (const content of tbody.querySelectorAll('.cell-value')) {
      const overflow = content.scrollHeight > content.clientHeight + 1;
      content.classList.toggle('is-scrollable', overflow);
      if (overflow) content.tabIndex = 0;
      else content.removeAttribute('tabindex');
    }
  }

  on(copy, 'click', async () => {
    update();
    const markdown = toMarkdown(data);
    copy.disabled = true;
    try {
      if (!navigator.clipboard?.writeText) throw new Error('Clipboard API unavailable');
      await navigator.clipboard.writeText(markdown);
      manual.hidden = true;
      status.textContent = 'Markdown 已复制。';
    } catch {
      manual.hidden = false;
      textarea.value = markdown;
      textarea.focus();
      textarea.select();
      let success = false;
      try { success = document.execCommand('copy'); } catch { /* 保留手动复制内容。 */ }
      status.textContent = success ? 'Markdown 已复制。' : '自动复制未成功，请复制已选中的 Markdown。';
      if (success) manual.hidden = true;
    } finally { copy.disabled = false; }
  });
  on(refresh, 'click', () => { update(true); status.textContent = '已重新提取当前页面。'; });
  on(collapse, 'click', () => {
    body.hidden = !body.hidden;
    collapse.textContent = body.hidden ? '+' : '−';
    collapse.setAttribute('aria-label', body.hidden ? '展开面板' : '收起面板');
    collapse.setAttribute('aria-expanded', String(!body.hidden));
    clampPosition();
    updateCellFocus();
  });
  function place(x, y) {
    const rect = host.getBoundingClientRect();
    host.style.setProperty('left', `${Math.max(0, Math.min(x, innerWidth - rect.width))}px`, 'important');
    host.style.setProperty('top', `${Math.max(0, Math.min(y, innerHeight - rect.height))}px`, 'important');
    host.style.setProperty('right', 'auto', 'important');
  }
  function clampPosition() { const rect = host.getBoundingClientRect(); place(rect.left, rect.top); }
  let drag = null;
  on(header, 'pointerdown', event => {
    if (event.button !== 0 || event.target.closest('button')) return;
    const rect = host.getBoundingClientRect();
    drag = { x: event.clientX - rect.left, y: event.clientY - rect.top, id: event.pointerId };
    header.setPointerCapture(event.pointerId);
    event.preventDefault();
  });
  on(header, 'pointermove', event => {
    if (drag && drag.id === event.pointerId) place(event.clientX - drag.x, event.clientY - drag.y);
  });
  for (const event of ['pointerup', 'pointercancel', 'lostpointercapture']) on(header, event, () => { drag = null; });
  on(window, 'resize', () => { clampPosition(); updateCellFocus(); });
  const schedule = () => { clearTimeout(timer); timer = setTimeout(() => update(), 450); };
  const observer = new MutationObserver(schedule);
  observer.observe(document.body, { childList: true, subtree: true, characterData: true,
    attributes: true, attributeFilter: ['href', 'class', 'style', 'hidden', 'aria-hidden', 'data-href', 'data-url', 'data-rurl', 'data-attrid'] });
  on(window, 'popstate', schedule);
  on(window, 'hashchange', schedule);
  const api = {
    get data() { return data; },
    refresh() { update(true); return data; },
    toMarkdown() { update(); return toMarkdown(data); },
    destroy() {
      disposed = true;
      observer.disconnect();
      controller.abort();
      clearTimeout(timer);
      host.remove();
      if (window[KEY] === api) delete window[KEY];
    }
  };
  window[KEY] = api;
  on(close, 'click', api.destroy);
  update(true);
  console.info('[MineTools] 当前页面采集面板已打开。');
  // executeScript must return a serializable result, not DOM nodes or functions.
  return { ok: true, resultCount: data.resultCount, metricsContainerCount: data.metricsContainerCount };
})();
