import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourcePath = path.join(root, 'src', 'content-script.js');
const outputPath = path.join(root, 'content.js');
let source = await readFile(sourcePath, 'utf8');

const replacements = new Map([
  [
    '// 粘贴到 Google 网页搜索结果页的 Console 执行，无外部依赖。',
    '// MineTools content script. Generated by scripts/build.mjs.\n' +
      '  // Chrome ISOLATED world; no page-script bridge or remote code.\n' +
      '  if (!document.body) return { ok: false };'
  ],
  ['__googleSerpExporter', '__mineToolsPanel'],
  ['google-serp-exporter-panel', 'minetools-panel'],
  ["'Google 搜索结果采集面板'", "'MineTools 搜索结果采集面板'"],
  ["el('div', 'Google 搜索结果', 'title')", "el('div', 'MineTools', 'title')"],
  ["'拖动此处移动面板'", "'Google 搜索采集 · 拖动此处移动面板'"],
  [
    "'[Google SERP Exporter] 已提取。结构化数据：window.__mineToolsPanel.data'",
    "'[MineTools] 当前页面采集面板已打开。'"
  ],
  [
    '  return api;',
    '  // executeScript must return a serializable result, not DOM nodes or functions.\n' +
      '  return { ok: true, resultCount: data.resultCount, metricsContainerCount: data.metricsContainerCount };'
  ]
]);

for (const [from, to] of replacements) {
  if (!source.includes(from)) throw new Error(`Source changed; missing build marker: ${JSON.stringify(from)}`);
  source = source.replaceAll(from, to);
}

await writeFile(outputPath, source.replace(/\r\n/g, '\n'), 'utf8');
console.log('Generated content.js from src/content-script.js.');
